### PR TITLE
Migrate to go mod

### PR DESCRIPTION
**Pull request by juanluisvaladas**
Looks like glide files were accidentally moved to /pkg on https://github.com/openshift/egress-router-cni/commit/f0a90fd0c06c6ad1f09259ac6f7c116b2090a25f

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
Initially I was moving glide.yaml and glide.lock to / but there isn't really a point doing a PR like that when we're moving to go.mod. I'll do a single PR with the whole migration.

**Comment by juanluisvaladas** [comment]
There are a few changes in the vendor but they seem safe:
- The vast majority of deletions are files that aren't necessary at all, go mod only keeps required files.
- Some new files are added from the go standard library, go mod does this.
- There are a few modified files but these look safe:

$ git show --summary | grep mode | grep -v -e 'delete mode' -e vendor/golang.org/x/ 
 mode change 100755 => 100644 vendor/github.com/googleapis/gnostic/extensions/COMPILE-EXTENSION.sh
 mode change 100755 => 100644 vendor/github.com/json-iterator/go/build.sh
 mode change 100755 => 100644 vendor/github.com/json-iterator/go/test.sh
 mode change 100755 => 100644 vendor/github.com/modern-go/concurrent/test.sh
 mode change 100755 => 100644 vendor/github.com/modern-go/reflect2/test.sh
 mode change 100755 => 100644 vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
 mode change 100755 => 100644 vendor/google.golang.org/appengine/internal/regen.sh
 create mode 100644 vendor/modules.txt

**Comment by juanluisvaladas** [comment]
@rcarrillocruz shouldn't the bot have merged this already?

**Comment by danwinship** [comment]
The approve didn't take but it also seems that tide isn't paying attention to this bug. (There's no list of statuses.). Maybe it needs more config in `openshift/release`?

/approve

**Comment by juanluisvaladas** [comment]
Yes, it looks like it needs more stuff... @knobunc merged the previous PRs manually.

**Comment by juanluisvaladas** [comment]
@knobunc you seem to have merge rights for this, can you please merge it?

**Pull request merged**
