### PR TITLE
Bug 1962740: Add documentation related CNO controller

### PR DESCRIPTION
**Pull request by danielmellado**
This PR adds documentation related CNO, logging and multiple
destinations' support.

### CODE REVIEW

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now 973ce7aec5a87a893753ec35b609f81cdf9614ea

**Comment by danielmellado** [comment]
Pull-request updated, HEAD is now d9d715819fda56a83b0c52f5ff59741786b3bc63

**Comment by danielmellado** [comment]
@astoycos mind creating a BZ and adding it to the label so tide can merge this?

**Comment by astoycos** [comment]
@danielmellado Can you add 1962740 to the title here?

**Pull request merged**
