### PR TITLE
Add build machinery go

### PR DESCRIPTION
**Pull request by juanluisvaladas**
This Does a bunch of stuff that we need in order to get openshift/release working:
1- Add build machinery-go as a dependency, and update vendor/ in a diffrentent commit
2- Create a basic makefile
3- A couple changes in the code so that make test-unit returns 0, the changes are minor nitpicks regarding apropriate use of fmt.Errorf
4- Add a make target to build the images.

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
/assign @danwinship
Hoping the bot is working now...

**Comment by danwinship** [comment]
hm... @juanluisvaladas 

>  tide Pending — Not mergeable. Merging to branch master is forbidden.

**Pull request merged**
